VERSION   = 0.1
NAME      = hp50


SCRIPT    = ./transcode.sed
IDE       = "C:\Program Files (x86)\HPUserEdit6\UserEdit.exe"
EMU       = "C:\Program Files (x86)\Hewlett-Packard\Debug4x\Emu\Emu48.exe"
DEBUG4X   = "C:\Program Files (x86)\Hewlett-Packard\Debug4x\Debug4x.exe"
MOUNT     = ./uff.sh

include hp.mk
